services:
  db:
    restart: always
    network_mode: host
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: forge-example
      POSTGRES_USER: forge-example
      POSTGRES_PASSWORD: forge-example
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U forge-example -d forge-example']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
