[package]
name = "forge-http"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
tracing = { version = "=0.1.44"}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
monoio = { version = "0.2.4" }