[package]
name = "forge-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.44"
proc-macro-crate = "3.4.0"
syn = { version = "2.0.114", features = ["proc-macro"] }

[lib]
proc-macro = true